export const faucets = [
  {
    slug: "lady",
    ticker: "LADY",
    name: "LadyChain",
    drip: "0.1",
    url: "https://ladyfaucet.online",
    native: true,
    accent: "#e8459e",
    accent2: "#3d1240",
  },
  // socials sourced from LadyCharts token_metadata table (June 2026)
  { slug: "sloth",   ticker: "SLOTH",   name: "Sloth Syndicate",     drip: "1,000",
    twitter: "https://x.com/jojovibes24" },
  { slug: "wisdog",  ticker: "WISDOG",  name: "Dog of Wisdom",       drip: "87,150" },
  { slug: "bitcoin", ticker: "BITCOIN", name: "Magic Internet Money", drip: "5" },
  { slug: "beans",   ticker: "BEANS",   name: "Coffeebeans",         drip: "1,000",
    telegram: "https://t.me/CoffeeholicsMetaCafe" },
  { slug: "boo",     ticker: "BOO",     name: "BOO",                 drip: "0.00001",
    twitter: "https://x.com/booxrpl?s=11" },
  { slug: "bullishclick", ticker: "BC", name: "Bullish Click",       drip: "0.71" },
  { slug: "lmax",    ticker: "LMAX",    name: "Ladyus Maximus",      drip: "250",
    telegram: "https://t.me/+XBadV0smnlphMDA0" },
  { slug: "cafe",    ticker: "CAFE",    name: "CAFE DOLLARS",        drip: "50,000,000" },
  { slug: "l589",    ticker: "L589",    name: "Lady589",             drip: "100",
    telegram: "https://t.me/+2bfm7fjD0Eo4NWQ8" },
  { slug: "giga",    ticker: "GIGA",    name: "GIGACHAD",            drip: "10",
    website: "https://gigaonxrp.com/",
    twitter: "https://x.com/XRPLGigaChad",
    telegram: "https://t.me/gigaonx" },
  { slug: "cbm",     ticker: "CBM",     name: "Cheese Burger Money", drip: "100" },
];
